"""add delivery error message

Revision ID: 16604885bdb1
Revises: a7a3ca6c49ed
Create Date: 2026-10-05 00:49:34.821317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16604885bdb1'
down_revision: Union[str, Sequence[str], None] = 'a7a3ca6c49ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_deliveries', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_deliveries', 'error_message')
    # ### end Alembic commands ###
